import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { PersistGate } from "redux-persist/integration/react";

import BottomDock from "./components/BottomDock";
import { persistor } from "./store/store";

const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Mood Tracker",
  description: "Generated by create next app",
  icons: "/icon512_rounded.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <link rel="manifest" href="/manifest.json" />
      <body className="max-w-2xl mx-auto border-x flex-col justify-center h-screen">
        <Providers>
          {/* <PersistGate loading={null} persistor={persistor}> */}
          {children}
          {/* </PersistGate> */}
        </Providers>
      </body>
    </html>
  );
}
